import type { Metadata } from "next";
import { Space_Grotesk, Inter } from "next/font/google";
import "./globals.css";
import MarketingChrome from "@/components/MarketingChrome";
import { Analytics } from "@vercel/analytics/next";
import { SpeedInsights } from "@vercel/speed-insights/next";
import AxeDevtools from "@/components/AxeDevtools";

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-display",
  display: "swap",
  weight: ["400", "500", "600", "700"],
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-body",
  display: "swap",
});

const SITE_URL = "https://centaurrobotics.com";
const TITLE = "Centaur — A wheelchair that lifts you to eye level";
const DESCRIPTION =
  "The Centaur is a self-balancing personal mobility chair that rises to eye level, fits through standard doorways and drops to the dining table. Built to automotive standards. In production — open for pre-order.";

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: TITLE,
  description: DESCRIPTION,
  alternates: { canonical: "/" },
  openGraph: {
    type: "website",
    url: SITE_URL,
    siteName: "Centaur Robotics",
    title: TITLE,
    description: DESCRIPTION,
    // OG image generated by app/opengraph-image.tsx — swap for product hero render before launch.
    images: [{ url: "/opengraph-image", width: 1200, height: 630, alt: "The Centaur" }],
  },
  twitter: {
    card: "summary_large_image",
    title: TITLE,
    description: DESCRIPTION,
    images: ["/opengraph-image"],
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en-GB" className={`${spaceGrotesk.variable} ${inter.variable}`}>
      <head>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@graph": [
                {
                  "@type": "Organization",
                  "@id": `${SITE_URL}/#organization`,
                  name: "Centaur Robotics",
                  url: SITE_URL,
                  logo: `${SITE_URL}/icon.svg`,
                  description: DESCRIPTION,
                  areaServed: "GB",
                },
                {
                  "@type": "Product",
                  name: "The Centaur",
                  category: "Self-balancing electric wheelchair",
                  description:
                    "A self-balancing wheelchair that rises to eye level (820mm), fits standard doorways (470mm) and lowers to the table (480mm). Engineered to automotive standards.",
                  brand: { "@id": `${SITE_URL}/#organization` },
                  // Real, published specs only — no invented figures, no pricing.
                  additionalProperty: [
                    { "@type": "PropertyValue", name: "Seat height range", value: "480–820mm" },
                    { "@type": "PropertyValue", name: "Width", value: "470mm" },
                    { "@type": "PropertyValue", name: "Top speed", value: "4mph" },
                    { "@type": "PropertyValue", name: "Range", value: "10+ miles" },
                  ],
                  offers: {
                    "@type": "Offer",
                    url: `${SITE_URL}/configure`,
                    availability: "https://schema.org/PreOrder",
                    // Pricing is handled off-site (by the team), so no price is published here.
                  },
                },
              ],
            }),
          }}
        />
      </head>
      <body className="font-sans antialiased">
        <a
          href="#main"
          className="sr-only focus:not-sr-only focus:fixed focus:left-4 focus:top-4 focus:z-[70] focus:rounded-full focus:bg-ink focus:px-5 focus:py-2 focus:font-sans focus:text-sm focus:text-bone"
        >
          Skip to content
        </a>
        <MarketingChrome>{children}</MarketingChrome>
        <Analytics />
        <SpeedInsights />
        <AxeDevtools />
      </body>
    </html>
  );
}
