import type { Metadata } from "next";
import { Space_Grotesk, Inter } from "next/font/google";
import "./globals.css";
import MarketingChrome from "@/components/MarketingChrome";

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-display",
  display: "swap",
  weight: ["400", "500", "600", "700"],
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-body",
  display: "swap",
});

const SITE_URL = "https://centaurrobotics.com";
const TITLE = "Centaur — A wheelchair that lifts you to eye level";
const DESCRIPTION =
  "The Centaur is a self-balancing personal mobility chair that rises to eye level, fits through standard doorways and drops to the dining table. Built to automotive standards. In production — open for pre-order.";

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: TITLE,
  description: DESCRIPTION,
  alternates: { canonical: "/" },
  openGraph: {
    type: "website",
    url: SITE_URL,
    siteName: "Centaur Robotics",
    title: TITLE,
    description: DESCRIPTION,
    // OG image generated by app/opengraph-image.tsx — swap for product hero render before launch.
    images: [{ url: "/opengraph-image", width: 1200, height: 630, alt: "The Centaur" }],
  },
  twitter: {
    card: "summary_large_image",
    title: TITLE,
    description: DESCRIPTION,
    images: ["/opengraph-image"],
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en-GB" className={`${spaceGrotesk.variable} ${inter.variable}`}>
      <head>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "Organization",
              name: "Centaur Robotics",
              url: SITE_URL,
              logo: `${SITE_URL}/icon.svg`,
              description: DESCRIPTION,
              makesOffer: {
                "@type": "Product",
                name: "The Centaur",
                category: "Self-balancing electric wheelchair",
                description:
                  "A self-balancing wheelchair that rises to eye level (820mm), fits standard doorways (470mm) and lowers to the table (480mm). Engineered to automotive standards.",
              },
            }),
          }}
        />
      </head>
      <body className="font-sans antialiased">
        <a
          href="#main"
          className="sr-only focus:not-sr-only focus:fixed focus:left-4 focus:top-4 focus:z-[70] focus:rounded-full focus:bg-ink focus:px-5 focus:py-2 focus:font-sans focus:text-sm focus:text-bone"
        >
          Skip to content
        </a>
        <MarketingChrome>{children}</MarketingChrome>
      </body>
    </html>
  );
}
